version: '3.8'

services:
    app:
        image: auth-server
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        environment:
            DB_HOST: db
            CONFIG_PATH: ${CONFIG_PATH}
        ports:
            - "8080:8080"
        depends_on:
            - db

    db:
        image: 'postgres:16.1'
        restart: no
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: auth
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
